### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by pvanheus** [jic-dtool/dtool-http#2]
I'm guess that this is MIT licensed like the rest of the dtool code but there is no LICENSE file supplied.

**Comment by tjelvar-olsson** [comment]
Thank you. It should also be MIT. I'll add it as soon as possible. :)

**Comment by pvanheus** [comment]
Thanks. I am busy preparing a conda recipe for dtool (for conda-forge) and
this is one of the details that people look out for.

**Comment by tjelvar-olsson** [comment]
Cool! I haven't gotten into the Conda universe yet. Please let me know how
you are getting along and if you need any help.

**Comment by tjelvar-olsson** [comment]
Added licence file to repo 2af839a

**Comment by pvanheus** [comment]
Thanks... please tag a new release.

**Comment by tjelvar-olsson** [comment]
Fix incorporated into 0.2.1 release of dtool-http
